security:
  password_hashers:
    App\Security\Domain\AdminUser: 'auto'

  providers:
    admin_provider:
      entity:
        class: App\Security\Domain\AdminUser
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: admin_provider
      form_login:
        login_path: app_login
        check_path: app_login
        enable_csrf: true
        default_target_path: admin_dashboard
      logout:
        path: app_logout
        target: app_login

  access_control:
    - { path: ^/admin/login, roles: PUBLIC_ACCESS }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/api, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: PUBLIC_ACCESS }
